package me.huizengek.swimrankingsscraper

import kotlinx.datetime.LocalDate
import kotlinx.serialization.Serializable
import kotlin.time.Duration

val countries = mapOf(
    -1 to "Wereldwijd",
    401 to "AFG - Afghanistan",
    402 to "AHO - Netherlands Antilles",
    403 to "ALB - Albania",
    404 to "ALG - Algeria",
    405 to "AND - Andorra",
    406 to "ANG - Angola",
    408 to "ANT - Antigua & Barbuda",
    409 to "ARG - Argentina",
    410 to "ARM - Armenia",
    411 to "ARU - Aruba",
    412 to "ASA - American Samoa",
    413 to "AUS - Australia",
    414 to "AUT - Austria",
    38 to "AZE - Azerbaijan",
    39 to "BAH - Bahamas",
    40 to "BAN - Bangladesh",
    41 to "BAR - Barbados",
    42 to "BDI - Burundi",
    43 to "BEL - Belgium",
    44 to "BEN - Benin",
    45 to "BER - Bermuda",
    46 to "BHU - Bhutan",
    47 to "BIH - Bosnia-Herzegovina",
    49 to "BIZ - Belize",
    50 to "BLR - Belarus",
    52 to "BOL - Bolivia",
    53 to "BOT - Botswana",
    54 to "BRA - Brazil",
    55 to "BRN - Bahrain",
    56 to "BRU - Brunei",
    57 to "BUL - Bulgaria",
    58 to "BUR - Burkina Faso",
    60 to "CAF - Central African Rep.",
    61 to "CAM - Cambodia",
    62 to "CAN - Canada",
    76 to "CAY - Cayman Islands",
    78 to "CGO - Congo",
    79 to "CHA - Chad",
    80 to "CHI - Chile",
    81 to "CHN - China",
    83 to "CIV - Ivory Coast",
    84 to "CMR - Cameroon",
    85 to "COD - Dem. Rep. of  Congo",
    86 to "COK - Cook Islands",
    87 to "COL - Colombia",
    88 to "COM - Comoros",
    89 to "CPV - Cape Verde",
    90 to "CRC - Costa Rica",
    91 to "CRO - Croatia",
    92 to "CUB - Cuba",
    451 to "CUR - Curacao",
    93 to "CYP - Cyprus",
    94 to "CZE - Czech Republic",
    95 to "DEN - Denmark",
    96 to "DJI - Djibouti",
    97 to "DMA - Dominica",
    98 to "DOM - Dominican Republic",
    99 to "ECU - Ecuador",
    100 to "EGY - Egypt",
    102 to "ERI - Eritrea",
    103 to "ESA - El Salvador",
    104 to "ESP - Spain",
    105 to "EST - Estonia",
    106 to "ETH - Ethiopia",
    109 to "FIJ - Fiji",
    110 to "FIN - Finland",
    112 to "FRA - France",
    107 to "FRO - Faroe Islands",
    142 to "FSM - Micronesia",
    143 to "GAB - Gabon",
    144 to "GAM - Gambia",
    146 to "GBR - Great Britain",
    154 to "GBS - Guinea-Bissau",
    156 to "GEO - Georgia",
    157 to "GEQ - Equatorial Guinea",
    158 to "GER - Germany",
    177 to "GHA - Ghana",
    178 to "GIB - Gibraltar",
    181 to "GRE - Greece",
    182 to "GRN - Grenada",
    183 to "GUA - Guatemala",
    185 to "GUI - Guinea",
    186 to "GUM - Guam",
    187 to "GUY - Guyana",
    188 to "HAI - Haiti",
    190 to "HKG - Hong Kong",
    191 to "HON - Honduras",
    192 to "HUN - Hungary",
    194 to "INA - Indonesia",
    195 to "IND - India",
    198 to "IRI - I. R. Iran",
    199 to "IRL - Ireland",
    226 to "IRQ - Iraq",
    227 to "ISL - Iceland",
    228 to "ISR - Israel",
    229 to "ISV - Virgin Islands",
    230 to "ITA - Italy",
    231 to "IVB - British Virgin Is.",
    232 to "JAM - Jamaica",
    233 to "JOR - Jordan",
    234 to "JPN - Japan",
    235 to "KAZ - Kazakhstan",
    236 to "KEN - Kenya",
    237 to "KGZ - Kyrgyzstan",
    238 to "KIR - Kiribati",
    239 to "KOR - Korea",
    75 to "KOS - Kosovo",
    240 to "KSA - Saudi Arabia",
    241 to "KUW - Kuwait",
    242 to "LAO - Laos PDR",
    243 to "LAT - Latvia",
    244 to "LBA - Libya",
    248 to "LBN - Lebanon",
    245 to "LBR - Liberia",
    246 to "LCA - Saint Lucia",
    247 to "LES - Lesotho",
    249 to "LIE - Liechtenstein",
    250 to "LTU - Lithuania",
    251 to "LUX - Luxembourg",
    63 to "MAA - Sint Maarten",
    252 to "MAC - Macau",
    253 to "MAD - Madagascar",
    254 to "MAR - Morocco",
    255 to "MAS - Malaysia",
    256 to "MAW - Malawi",
    257 to "MDA - Moldova",
    258 to "MDV - Maldives",
    259 to "MEX - Mexico",
    260 to "MGL - Mongolia",
    262 to "MHL - Marshall Islands",
    263 to "MKD - Fr. Yug. Rep. Macedonia",
    264 to "MLI - Mali",
    265 to "MLT - Malta",
    416 to "MNE - Montenegro",
    266 to "MON - Monaco",
    267 to "MOZ - Mozambique",
    268 to "MRI - Mauritius",
    269 to "MTN - Mauritania",
    270 to "MYA - Myanmar",
    271 to "NAM - Namibia",
    272 to "NCA - Nicaragua",
    273 to "NED - Netherlands",
    274 to "NEP - Nepal",
    275 to "NGR - Nigeria",
    276 to "NIG - Niger",
    278 to "NMA - Mariannes Islands",
    279 to "NOR - Norway",
    280 to "NRU - Nauru",
    281 to "NZL - New Zealand",
    282 to "OMA - Oman",
    283 to "PAK - Pakistan",
    284 to "PAN - Panama",
    285 to "PAR - Paraguay",
    286 to "PER - Peru",
    287 to "PHI - Philippines",
    288 to "PLE - Palestine",
    289 to "PLW - Palau",
    290 to "PNG - Papua New Guinea",
    291 to "POL - Poland",
    308 to "POR - Portugal",
    321 to "PRK - DPR Korea",
    322 to "PUR - Puerto Rico",
    323 to "QAT - Qatar",
    325 to "ROU - Romania",
    326 to "RSA - South Africa",
    327 to "RUS - Russia",
    328 to "RWA - Rwanda",
    330 to "SAM - Samoa",
    333 to "SEN - Senegal",
    334 to "SEY - Seychelles",
    335 to "SGP - Singapore",
    336 to "SKN - St. Kitts & Nevis",
    337 to "SLE - Sierra Leone",
    338 to "SLO - Slovenia",
    339 to "SMR - San Marino",
    341 to "SOL - Solomon Islands",
    342 to "SOM - Somalia",
    415 to "SRB - Serbia",
    343 to "SRI - Sri Lanka",
    344 to "STP - S. Tome & Principe",
    345 to "SUD - Sudan",
    346 to "SUI - Switzerland",
    352 to "SUR - Suriname",
    353 to "SVK - Slovakia",
    354 to "SWE - Sweden",
    355 to "SWZ - Swaziland",
    356 to "SYR - Syria",
    357 to "TAH - Tahiti",
    358 to "TAN - Tanzania",
    64 to "TCN - Turks and Caicos Islands",
    360 to "TGA - Tonga",
    361 to "THA - Thailand",
    362 to "TJK - Tajikistan",
    363 to "TKM - Turkmenistan",
    364 to "TLS - Timor-Leste",
    366 to "TOG - Togo",
    367 to "TPE - Chinese Taipei",
    368 to "TTO - Trinidad &Tobago",
    370 to "TUN - Tunisia",
    371 to "TUR - Turkey",
    108 to "TUV - Tuvalu",
    372 to "UAE - United Arab Emirates",
    373 to "UGA - Uganda",
    375 to "UKR - Ukraine",
    377 to "URU - Uruguay",
    378 to "USA - United States",
    438 to "UZB - Uzbekistan",
    439 to "VAN - Vanuatu",
    440 to "VEN - Venezuela",
    441 to "VIE - Vietnam",
    442 to "VIN - St. Vincent & Grenadines",
    445 to "YEM - Yemen",
    449 to "ZAM - Zambia",
    450 to "ZIM - Zimbabwe"
)

@Serializable
data class SearchQuery(
    val firstName: String = "",
    val lastName: String = "",
    val gender: Gender = Gender.UNSPECIFIED,
    val country: Int = -1
)

@Serializable
data class SearchResults(
    val results: List<Athlete>
)

@Serializable
data class Athlete(
    val id: Int,
    val name: String,
    val birthdate: String,
    val country: String,
    val club: String
)

@Serializable
data class Records(
    val athleteId: Int,
    val results: List<Record>
)

@Serializable
data class Record(
    val event: Event,
    val result: RecordResult,
    val points: Int?,
    val date: LocalDate,
    val city: String,
    val match: Match
)

@Serializable
data class Event(
    val id: Int,
    val description: String,
    val link: String,
    val course: String
)

@Serializable
data class RecordResult(
    val id: Int,
    val rawValue: String,
    val link: String,
    @Serializable(with = DurationSerializer::class)
    val time: Duration
)

@Serializable
data class Match(
    val id: Int,
    val name: String,
    val link: String
)

@Serializable
enum class Gender(val id: Int) {
    UNSPECIFIED(-1),
    MAN(1),
    WOMAN(2)
}